# Need this else Travis gives warnings
language: python
python:
  - "3.5"
#  - "3.6"

addons:
  apt:
    packages:
#    - libgeos-dev
#    - proj4

# Need this rigmarole just to install PROJ.4 for Cartopy
sudo: true
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev proj-bin proj-data
  - sudo apt-get install -y python-pyproj
  - sudo apt-get install -y libc6
  - wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj9_4.9.2-2_amd64.deb 
  - sudo dpkg -i libproj9_4.9.2-2_amd64.deb 
  - wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_4.9.2-2_amd64.deb
  - sudo dpkg -i libproj-dev_4.9.2-2_amd64.deb
# For mock mail service
  - sudo apt-get install -y -qq postfix

# For mock mail service
before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

notifications:
  email: false

# command to install dependencies
install: 
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest-cov

# command to run tests
script: pytest --cov=dyfi tests/test.py tests/test_run.py

# Now run codecov
after_success:
    - pip install codecov 
    - codecov
    - coverage xml
#    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
