# Need this else Travis gives warnings
language: python
python:
  - "3.5"
#  - "3.6"

addons:
  apt:
    packages:
#     - pov-wkhtmltopdf
#    - libgeos-dev
#    - proj4

before_install:
  - sudo add-apt-repository -y ppa:pov/wkhtmltopdf
  - sudo apt-get -qq update
#  - sudo apt-get install -y python-pyproj
#  - sudo apt-get install -y libc6
  - sudo apt-get install -y wkhtmltopdf
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# For mock mail service
  - sudo apt-get install -y -qq postfix

# For mock mail service
before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

notifications:
  email: false

# command to install dependencies
install: 
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest-cov

# command to run tests
script: pytest --cov=dyfi tests/test.py tests/test_run.py

# Now run codecov
after_success:
    - pip install codecov 
    - codecov
    - coverage xml
#    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
