# Sample config.yml
# Executables and tests must be run in the package root directory
# Hence data directories, databases, etc. should be specified from package root

db:
    # type is either mysql or sqlite3
    type: sqlite3
    files: 
        event: tests/db/event.db
        maps: tests/db/maps.db
        extended: tests/db/__EXTENDED__.db

directories:        
    data: data
    leaflet: leaflet
    incoming: data/incoming
    trashincoming: data/.trash-incoming
    badincoming : data/badincoming

executables:
    screenshot: 
      - phantomjs
      - __ABSPATH__/capture.js

products:
    file: lib/products.yml

filter:
    maxdist: 3000
    nresp_do_not_filter: 3
    int_diff_threshold: 2
    int_low_threshold: 0

