# Sample config.yml
# Executables and tests must be run in the package root directory
# Hence data directories, databases, etc. should be specified from package root

mail:
    to: alerts@server.gov
    operator: operator@server.gov
    smtp: smtp.server.gov
    mailbin: /usr/bin/mail

db:
    # type is either mysql or sqlite3
    type: sqlite3
    files: 
        event: tests/db/event.db
        maps: tests/db/maps.db
        extended: tests/db/__EXTENDED__.db

directories:        
    data: data
    leaflet: leaflet

# Use google chrome headless
#executables:
#    screenshot: 
      # Use this for Mac; alias does not work for subprocess.run
      #- /Applications/Google Chrome.app/Contents/MacOS/Google Chrome  
      #- --headless
      #- --disable-gpu
      #- --screenshot
      #- file://__ABSPATH__/viewer.html 
      #- file://__ABSPATH__/capture.js

# Use phantomjs
executables:
    screenshot: 
      - phantomjs
      - __ABSPATH__/capture.js

