channels:
- conda-forge
- defaults
dependencies:
- geopy
- numpy
- phantomjs>=2.1.1
- pytest
- pytest-cov
- python=3.5
- pyyaml
- pip:
  - apng
  - codecov
  - defusedxml
  - geojson
  - sphinx-argparse>=0.2.1
