channels:
- conda-forge
- defaults
dependencies:
- codecov
- defusedxml
- geojson
- geopy
- numpy
- phantomjs>=2.1.1
- pytest
- pytest-cov
- python=3.5
- pyyaml
- sphinx-argparse>=0.2.1
- sqlite
- pip:
  - apng
