# Sample config.yml for the util directory.
# Used by util programs 
# (updateEvent.py, loadEntries.py, queueTriggers.py, etc.)

# Executables and tests must be run in the package root directory
# Hence data directories, databases, etc. should be specified from package root 

db:
    # type is either mysql or sqlite3
    type: sqlite3
    files:
        event: tests/db/event.db
        geonames: tests/db/geonames.db
        maps: tests/db/maps.db
        extended: tests/db/__EXTENDED__.db

# Test directories. For production, change to data/incoming etc.
directories:        
    incoming: data/incoming
    trashincoming: data/trashincoming
    badincoming: data/badincoming
    flags: flags

executables:
    push: bin/push.py --trigger
    run: app/rundyfi.py

pending:
    delay: 120

comcat:
    server: earthquake.usgs.gov
    urlbase: https://__SERVER__/fdsnws/event/1/query?
    timeout: 15

geoserve:
    server: earthquake.usgs.gov
    urlbase: https://__SERVER__/ws/geoserve/places.json?
    timeout: 15

